// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DefaultError struct {
	Msg *string `json:"msg,omitempty"`
}

func (o *DefaultError) GetMsg() *string {
	if o == nil {
		return nil
	}
	return o.Msg
}
