// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TwoHundredSuccess - Successful Response
type TwoHundredSuccess struct {
	Success *bool `json:"success,omitempty"`
}
