// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TwoHundredSuccess struct {
	Success *bool `json:"success,omitempty"`
}

func (o *TwoHundredSuccess) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}
