// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ZoneGcpConfigNetworkServer struct {
	ID *string `json:"id,omitempty"`
}

type ZoneGcpConfig struct {
	ApplianceURL        *string                     `json:"applianceUrl,omitempty"`
	BackupMode          *string                     `json:"backupMode,omitempty"`
	CertificateProvider *string                     `json:"certificateProvider,omitempty"`
	ClientEmail         *string                     `json:"clientEmail,omitempty"`
	ConfigManagementID  *string                     `json:"configManagementId,omitempty"`
	DatacenterName      *string                     `json:"datacenterName,omitempty"`
	DNSIntegrationID    *string                     `json:"dnsIntegrationId,omitempty"`
	GoogleRegionID      *string                     `json:"googleRegionId,omitempty"`
	ImportExisting      *string                     `json:"importExisting,omitempty"`
	NetworkServer       *ZoneGcpConfigNetworkServer `json:"networkServer,omitempty"`
	NetworkServerID     *string                     `json:"networkServer.id,omitempty"`
	PrivateKey          *string                     `json:"privateKey,omitempty"`
	PrivateKeyHash      *string                     `json:"privateKeyHash,omitempty"`
	ProjectID           *string                     `json:"projectId,omitempty"`
	ReplicationMode     *string                     `json:"replicationMode,omitempty"`
	SecurityServer      *string                     `json:"securityServer,omitempty"`
	ServiceRegistryID   *string                     `json:"serviceRegistryId,omitempty"`
}
