// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"newtest/internal/sdk/pkg/utils"
)

// ZoneCreateConfig - Map containing zone configuration settings. See the section on specific zone types for details.
type ZoneCreateConfig struct {
}

// ZoneCreateCredential - Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
type ZoneCreateCredential struct {
	ID   *int64  `json:"id,omitempty"`
	Type *string `default:"local" json:"type"`
}

func (z ZoneCreateCredential) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(z, "", false)
}

func (z *ZoneCreateCredential) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &z, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ZoneCreateCredential) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ZoneCreateCredential) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

// Visibility - private or public
type Visibility string

const (
	VisibilityPrivate Visibility = "private"
	VisibilityPublic  Visibility = "public"
)

func (e Visibility) ToPointer() *Visibility {
	return &e
}

func (e *Visibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "public":
		*e = Visibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Visibility: %v", v)
	}
}

// ZoneCreate2 - Map containing the Cloud (zone) code name. See the zone-types API to fetch a list of all available Cloud (zone) types and their codes.
type ZoneCreate2 struct {
	Code *string `json:"code,omitempty"`
}

func (o *ZoneCreate2) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

// ZoneCreate1 - Map containing the Cloud (zone) type ID. See the zone-types API to fetch a list of all available Cloud (zone) types and their IDs.
type ZoneCreate1 struct {
	ID *int64 `json:"id,omitempty"`
}

func (o *ZoneCreate1) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

type ZoneCreateZoneTypeType string

const (
	ZoneCreateZoneTypeTypeZoneCreate1 ZoneCreateZoneTypeType = "zoneCreate_1"
	ZoneCreateZoneTypeTypeZoneCreate2 ZoneCreateZoneTypeType = "zoneCreate_2"
)

type ZoneCreateZoneType struct {
	ZoneCreate1 *ZoneCreate1
	ZoneCreate2 *ZoneCreate2

	Type ZoneCreateZoneTypeType
}

func CreateZoneCreateZoneTypeZoneCreate1(zoneCreate1 ZoneCreate1) ZoneCreateZoneType {
	typ := ZoneCreateZoneTypeTypeZoneCreate1

	return ZoneCreateZoneType{
		ZoneCreate1: &zoneCreate1,
		Type:        typ,
	}
}

func CreateZoneCreateZoneTypeZoneCreate2(zoneCreate2 ZoneCreate2) ZoneCreateZoneType {
	typ := ZoneCreateZoneTypeTypeZoneCreate2

	return ZoneCreateZoneType{
		ZoneCreate2: &zoneCreate2,
		Type:        typ,
	}
}

func (u *ZoneCreateZoneType) UnmarshalJSON(data []byte) error {

	zoneCreate1 := new(ZoneCreate1)
	if err := utils.UnmarshalJSON(data, &zoneCreate1, "", true, true); err == nil {
		u.ZoneCreate1 = zoneCreate1
		u.Type = ZoneCreateZoneTypeTypeZoneCreate1
		return nil
	}

	zoneCreate2 := new(ZoneCreate2)
	if err := utils.UnmarshalJSON(data, &zoneCreate2, "", true, true); err == nil {
		u.ZoneCreate2 = zoneCreate2
		u.Type = ZoneCreateZoneTypeTypeZoneCreate2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ZoneCreateZoneType) MarshalJSON() ([]byte, error) {
	if u.ZoneCreate1 != nil {
		return utils.MarshalJSON(u.ZoneCreate1, "", true)
	}

	if u.ZoneCreate2 != nil {
		return utils.MarshalJSON(u.ZoneCreate2, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type ZoneCreate struct {
	// Specifies which Tenant this cloud should be assigned to
	AccountID *int64 `json:"accountId,omitempty"`
	// Automatically Power on VMs
	AutoRecoverPowerState *bool `default:"false" json:"autoRecoverPowerState"`
	// Optional code for use with policies
	Code *string `json:"code,omitempty"`
	// Map containing zone configuration settings. See the section on specific zone types for details.
	Config *ZoneCreateConfig `json:"config,omitempty"`
	// Map containing Credential ID. Setting `type` to `local` means use the values set in the local cloud config instead of associating a credential.
	Credential *ZoneCreateCredential `json:"credential,omitempty"`
	// Optional description field if you want to put more info there
	Description *string `json:"description,omitempty"`
	// Can be used to disable the cloud
	Enabled *bool `default:"true" json:"enabled"`
	// Specifies which Server group this cloud should be assigned to
	GroupID int64 `json:"groupId"`
	// Linked Account ID (enter commercial ID to get costing for AWS Govcloud)
	LinkedAccountID *int64 `json:"linkedAccountId,omitempty"`
	// Optional location for your cloud
	Location *string `json:"location,omitempty"`
	// A unique name scoped to your account for the cloud
	Name string `json:"name"`
	// Scale Priority
	ScalePriority *int64 `default:"1" json:"scalePriority"`
	// host firewall. `off` or `internal`. a.k.a. "local firewall"
	SecurityMode *string `default:"off" json:"securityMode"`
	// private or public
	Visibility *Visibility        `default:"private" json:"visibility"`
	ZoneType   ZoneCreateZoneType `json:"zoneType"`
}

func (z ZoneCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(z, "", false)
}

func (z *ZoneCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &z, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ZoneCreate) GetAccountID() *int64 {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *ZoneCreate) GetAutoRecoverPowerState() *bool {
	if o == nil {
		return nil
	}
	return o.AutoRecoverPowerState
}

func (o *ZoneCreate) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ZoneCreate) GetConfig() *ZoneCreateConfig {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *ZoneCreate) GetCredential() *ZoneCreateCredential {
	if o == nil {
		return nil
	}
	return o.Credential
}

func (o *ZoneCreate) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ZoneCreate) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *ZoneCreate) GetGroupID() int64 {
	if o == nil {
		return 0
	}
	return o.GroupID
}

func (o *ZoneCreate) GetLinkedAccountID() *int64 {
	if o == nil {
		return nil
	}
	return o.LinkedAccountID
}

func (o *ZoneCreate) GetLocation() *string {
	if o == nil {
		return nil
	}
	return o.Location
}

func (o *ZoneCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ZoneCreate) GetScalePriority() *int64 {
	if o == nil {
		return nil
	}
	return o.ScalePriority
}

func (o *ZoneCreate) GetSecurityMode() *string {
	if o == nil {
		return nil
	}
	return o.SecurityMode
}

func (o *ZoneCreate) GetVisibility() *Visibility {
	if o == nil {
		return nil
	}
	return o.Visibility
}

func (o *ZoneCreate) GetZoneType() ZoneCreateZoneType {
	if o == nil {
		return ZoneCreateZoneType{}
	}
	return o.ZoneType
}
