// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
	"time"
)

type ZoneAccount struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ZoneConfigType string

const (
	ZoneConfigTypeZoneVcenterConfig ZoneConfigType = "zoneVcenterConfig"
	ZoneConfigTypeZoneAwsConfig     ZoneConfigType = "zoneAwsConfig"
	ZoneConfigTypeZoneAzureConfig   ZoneConfigType = "zoneAzureConfig"
	ZoneConfigTypeZoneGcpConfig     ZoneConfigType = "zoneGcpConfig"
)

type ZoneConfig struct {
	ZoneVcenterConfig *ZoneVcenterConfig
	ZoneAwsConfig     *ZoneAwsConfig
	ZoneAzureConfig   *ZoneAzureConfig
	ZoneGcpConfig     *ZoneGcpConfig

	Type ZoneConfigType
}

func CreateZoneConfigZoneVcenterConfig(zoneVcenterConfig ZoneVcenterConfig) ZoneConfig {
	typ := ZoneConfigTypeZoneVcenterConfig

	return ZoneConfig{
		ZoneVcenterConfig: &zoneVcenterConfig,
		Type:              typ,
	}
}

func CreateZoneConfigZoneAwsConfig(zoneAwsConfig ZoneAwsConfig) ZoneConfig {
	typ := ZoneConfigTypeZoneAwsConfig

	return ZoneConfig{
		ZoneAwsConfig: &zoneAwsConfig,
		Type:          typ,
	}
}

func CreateZoneConfigZoneAzureConfig(zoneAzureConfig ZoneAzureConfig) ZoneConfig {
	typ := ZoneConfigTypeZoneAzureConfig

	return ZoneConfig{
		ZoneAzureConfig: &zoneAzureConfig,
		Type:            typ,
	}
}

func CreateZoneConfigZoneGcpConfig(zoneGcpConfig ZoneGcpConfig) ZoneConfig {
	typ := ZoneConfigTypeZoneGcpConfig

	return ZoneConfig{
		ZoneGcpConfig: &zoneGcpConfig,
		Type:          typ,
	}
}

func (u *ZoneConfig) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	zoneAwsConfig := new(ZoneAwsConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneAwsConfig); err == nil {
		u.ZoneAwsConfig = zoneAwsConfig
		u.Type = ZoneConfigTypeZoneAwsConfig
		return nil
	}

	zoneVcenterConfig := new(ZoneVcenterConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneVcenterConfig); err == nil {
		u.ZoneVcenterConfig = zoneVcenterConfig
		u.Type = ZoneConfigTypeZoneVcenterConfig
		return nil
	}

	zoneGcpConfig := new(ZoneGcpConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneGcpConfig); err == nil {
		u.ZoneGcpConfig = zoneGcpConfig
		u.Type = ZoneConfigTypeZoneGcpConfig
		return nil
	}

	zoneAzureConfig := new(ZoneAzureConfig)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneAzureConfig); err == nil {
		u.ZoneAzureConfig = zoneAzureConfig
		u.Type = ZoneConfigTypeZoneAzureConfig
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ZoneConfig) MarshalJSON() ([]byte, error) {
	if u.ZoneAwsConfig != nil {
		return json.Marshal(u.ZoneAwsConfig)
	}

	if u.ZoneVcenterConfig != nil {
		return json.Marshal(u.ZoneVcenterConfig)
	}

	if u.ZoneGcpConfig != nil {
		return json.Marshal(u.ZoneGcpConfig)
	}

	if u.ZoneAzureConfig != nil {
		return json.Marshal(u.ZoneAzureConfig)
	}

	return nil, nil
}

type ZoneCredential2 struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

type ZoneCredential1 struct {
	Type *string `json:"type,omitempty"`
}

type ZoneCredentialType string

const (
	ZoneCredentialTypeZoneCredential1 ZoneCredentialType = "zone_credential_1"
	ZoneCredentialTypeZoneCredential2 ZoneCredentialType = "zone_credential_2"
)

type ZoneCredential struct {
	ZoneCredential1 *ZoneCredential1
	ZoneCredential2 *ZoneCredential2

	Type ZoneCredentialType
}

func CreateZoneCredentialZoneCredential1(zoneCredential1 ZoneCredential1) ZoneCredential {
	typ := ZoneCredentialTypeZoneCredential1

	return ZoneCredential{
		ZoneCredential1: &zoneCredential1,
		Type:            typ,
	}
}

func CreateZoneCredentialZoneCredential2(zoneCredential2 ZoneCredential2) ZoneCredential {
	typ := ZoneCredentialTypeZoneCredential2

	return ZoneCredential{
		ZoneCredential2: &zoneCredential2,
		Type:            typ,
	}
}

func (u *ZoneCredential) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	zoneCredential1 := new(ZoneCredential1)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneCredential1); err == nil {
		u.ZoneCredential1 = zoneCredential1
		u.Type = ZoneCredentialTypeZoneCredential1
		return nil
	}

	zoneCredential2 := new(ZoneCredential2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&zoneCredential2); err == nil {
		u.ZoneCredential2 = zoneCredential2
		u.Type = ZoneCredentialTypeZoneCredential2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u ZoneCredential) MarshalJSON() ([]byte, error) {
	if u.ZoneCredential1 != nil {
		return json.Marshal(u.ZoneCredential1)
	}

	if u.ZoneCredential2 != nil {
		return json.Marshal(u.ZoneCredential2)
	}

	return nil, nil
}

type ZoneGroups struct {
	AccountID *int64  `json:"accountId,omitempty"`
	ID        *int64  `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
}

type ZoneNetworkDomain struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ZoneNetworkServer struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ZoneOwner struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ZoneSecurityServer struct {
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ZoneStatsServerCounts struct {
	All           *int64 `json:"all,omitempty"`
	Baremetal     *int64 `json:"baremetal,omitempty"`
	ContainerHost *int64 `json:"containerHost,omitempty"`
	Host          *int64 `json:"host,omitempty"`
	Hypervisor    *int64 `json:"hypervisor,omitempty"`
	Unmanaged     *int64 `json:"unmanaged,omitempty"`
	VM            *int64 `json:"vm,omitempty"`
}

type ZoneStats struct {
	ServerCounts *ZoneStatsServerCounts `json:"serverCounts,omitempty"`
}

type ZoneZoneType struct {
	Code *string `json:"code,omitempty"`
	ID   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type Zone struct {
	Account               *ZoneAccount    `json:"account,omitempty"`
	AccountID             *int64          `json:"accountId,omitempty"`
	AgentMode             *string         `json:"agentMode,omitempty"`
	APIProxy              *string         `json:"apiProxy,omitempty"`
	AutoRecoverPowerState *bool           `json:"autoRecoverPowerState,omitempty"`
	Code                  *string         `json:"code,omitempty"`
	Config                *ZoneConfig     `json:"config,omitempty"`
	ConsoleKeymap         *string         `json:"consoleKeymap,omitempty"`
	ContainerMode         *string         `json:"containerMode,omitempty"`
	CostLastSync          *time.Time      `json:"costLastSync,omitempty"`
	CostLastSyncDuration  *int64          `json:"costLastSyncDuration,omitempty"`
	CostStatus            *string         `json:"costStatus,omitempty"`
	CostStatusDate        *time.Time      `json:"costStatusDate,omitempty"`
	CostStatusMessage     *string         `json:"costStatusMessage,omitempty"`
	CostingMode           *string         `json:"costingMode,omitempty"`
	Credential            *ZoneCredential `json:"credential,omitempty"`
	// Dark logo image URL
	DarkImagePath *string      `json:"darkImagePath,omitempty"`
	DateCreated   *time.Time   `json:"dateCreated,omitempty"`
	DomainName    *string      `json:"domainName,omitempty"`
	Enabled       *bool        `json:"enabled,omitempty"`
	ExternalID    *string      `json:"externalId,omitempty"`
	Groups        []ZoneGroups `json:"groups,omitempty"`
	GuidanceMode  *string      `json:"guidanceMode,omitempty"`
	ID            *int64       `json:"id,omitempty"`
	// Logo image URL
	ImagePath         *string             `json:"imagePath,omitempty"`
	InventoryLevel    *string             `json:"inventoryLevel,omitempty"`
	LastSync          *time.Time          `json:"lastSync,omitempty"`
	LastSyncDuration  *int64              `json:"lastSyncDuration,omitempty"`
	LastUpdated       *time.Time          `json:"lastUpdated,omitempty"`
	Location          *string             `json:"location,omitempty"`
	Name              *string             `json:"name,omitempty"`
	NetworkDomain     *ZoneNetworkDomain  `json:"networkDomain,omitempty"`
	NetworkServer     *ZoneNetworkServer  `json:"networkServer,omitempty"`
	NextRunDate       *time.Time          `json:"nextRunDate,omitempty"`
	Owner             *ZoneOwner          `json:"owner,omitempty"`
	ProvisioningProxy *string             `json:"provisioningProxy,omitempty"`
	RegionCode        *string             `json:"regionCode,omitempty"`
	ScalePriority     *int64              `json:"scalePriority,omitempty"`
	SecurityMode      *string             `json:"securityMode,omitempty"`
	SecurityServer    *ZoneSecurityServer `json:"securityServer,omitempty"`
	ServerCount       *int64              `json:"serverCount,omitempty"`
	ServiceVersion    *string             `json:"serviceVersion,omitempty"`
	Stats             *ZoneStats          `json:"stats,omitempty"`
	Status            *string             `json:"status,omitempty"`
	StatusDate        *time.Time          `json:"statusDate,omitempty"`
	StatusMessage     *string             `json:"statusMessage,omitempty"`
	StorageMode       *string             `json:"storageMode,omitempty"`
	Timezone          *string             `json:"timezone,omitempty"`
	UserDataLinux     *string             `json:"userDataLinux,omitempty"`
	UserDataWindows   *string             `json:"userDataWindows,omitempty"`
	UUID              *string             `json:"uuid,omitempty"`
	Visibility        *string             `json:"visibility,omitempty"`
	ZoneType          *ZoneZoneType       `json:"zoneType,omitempty"`
	ZoneTypeID        *int64              `json:"zoneTypeId,omitempty"`
}
