// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Groups struct {
	AccountID types.Int64  `tfsdk:"account_id"`
	ID        types.Int64  `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
}
