// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ZoneAwsConfig struct {
	UseHostCredentials   types.String                    `tfsdk:"use_host_credentials"`
	AccessKey            types.String                    `tfsdk:"access_key"`
	ApplianceURL         types.String                    `tfsdk:"appliance_url"`
	BackupMode           types.String                    `tfsdk:"backup_mode"`
	CertificateProvider  types.String                    `tfsdk:"certificate_provider"`
	ConfigCmdbDiscovery  types.Bool                      `tfsdk:"config_cmdb_discovery"`
	ConfigManagementID   types.String                    `tfsdk:"config_management_id"`
	CostingAccessKey     types.String                    `tfsdk:"costing_access_key"`
	CostingBucket        types.String                    `tfsdk:"costing_bucket"`
	CostingBucketName    types.String                    `tfsdk:"costing_bucket_name"`
	CostingFolder        types.String                    `tfsdk:"costing_folder"`
	CostingRegion        types.String                    `tfsdk:"costing_region"`
	CostingReport        types.String                    `tfsdk:"costing_report"`
	CostingReportName    types.String                    `tfsdk:"costing_report_name"`
	CostingSecretKey     types.String                    `tfsdk:"costing_secret_key"`
	CostingSecretKeyHash types.String                    `tfsdk:"costing_secret_key_hash"`
	DatacenterName       types.String                    `tfsdk:"datacenter_name"`
	DNSIntegrationID     types.String                    `tfsdk:"dns_integration_id"`
	EbsEncryption        types.String                    `tfsdk:"ebs_encryption"`
	Endpoint             types.String                    `tfsdk:"endpoint"`
	ImageStoreID         types.String                    `tfsdk:"image_store_id"`
	IsVpc                types.String                    `tfsdk:"is_vpc"`
	NetworkServer        *ZoneVcenterConfigNetworkServer `tfsdk:"network_server"`
	NetworkServerID      types.String                    `tfsdk:"network_server_id"`
	ReplicationMode      types.String                    `tfsdk:"replication_mode"`
	SecretKey            types.String                    `tfsdk:"secret_key"`
	SecretKeyHash        types.String                    `tfsdk:"secret_key_hash"`
	SecurityServer       types.String                    `tfsdk:"security_server"`
	ServiceRegistryID    types.String                    `tfsdk:"service_registry_id"`
	StsAssumeRole        types.String                    `tfsdk:"sts_assume_role"`
	Vpc                  types.String                    `tfsdk:"vpc"`
}
