// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ZoneGcpConfig struct {
	ApplianceURL        types.String                    `tfsdk:"appliance_url"`
	BackupMode          types.String                    `tfsdk:"backup_mode"`
	CertificateProvider types.String                    `tfsdk:"certificate_provider"`
	ClientEmail         types.String                    `tfsdk:"client_email"`
	ConfigManagementID  types.String                    `tfsdk:"config_management_id"`
	DatacenterName      types.String                    `tfsdk:"datacenter_name"`
	DNSIntegrationID    types.String                    `tfsdk:"dns_integration_id"`
	GoogleRegionID      types.String                    `tfsdk:"google_region_id"`
	ImportExisting      types.String                    `tfsdk:"import_existing"`
	NetworkServer       *ZoneVcenterConfigNetworkServer `tfsdk:"network_server"`
	NetworkServerID     types.String                    `tfsdk:"network_server_id"`
	PrivateKey          types.String                    `tfsdk:"private_key"`
	PrivateKeyHash      types.String                    `tfsdk:"private_key_hash"`
	ProjectID           types.String                    `tfsdk:"project_id"`
	ReplicationMode     types.String                    `tfsdk:"replication_mode"`
	SecurityServer      types.String                    `tfsdk:"security_server"`
	ServiceRegistryID   types.String                    `tfsdk:"service_registry_id"`
}
