// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ZoneCreateZoneType struct {
	ZoneCreate1 *ZoneCreate1 `tfsdk:"zone_create_1"`
	ZoneCreate2 *ZoneCreate2 `tfsdk:"zone_create_2"`
}
