// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type ZoneType struct {
	Code types.String `tfsdk:"code"`
	ID   types.Int64  `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
