// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ZoneCreateZoneType struct {
	ZoneCreateZoneType1 *ZoneCreateZoneType1 `tfsdk:"zone_create_zone_type_1"`
	ZoneCreateZoneType2 *ZoneCreateZoneType2 `tfsdk:"zone_create_zone_type_2"`
}
