// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Zone struct {
	Account               *Account     `tfsdk:"account"`
	AccountID             types.Int64  `tfsdk:"account_id"`
	AgentMode             types.String `tfsdk:"agent_mode"`
	APIProxy              types.String `tfsdk:"api_proxy"`
	AutoRecoverPowerState types.Bool   `tfsdk:"auto_recover_power_state"`
	Code                  types.String `tfsdk:"code"`
	Config                *Config      `tfsdk:"config"`
	ConsoleKeymap         types.String `tfsdk:"console_keymap"`
	ContainerMode         types.String `tfsdk:"container_mode"`
	CostingMode           types.String `tfsdk:"costing_mode"`
	CostLastSync          types.String `tfsdk:"cost_last_sync"`
	CostLastSyncDuration  types.Int64  `tfsdk:"cost_last_sync_duration"`
	CostStatus            types.String `tfsdk:"cost_status"`
	CostStatusDate        types.String `tfsdk:"cost_status_date"`
	CostStatusMessage     types.String `tfsdk:"cost_status_message"`
	Credential            *Credential  `tfsdk:"credential"`
	DarkImagePath         types.String `tfsdk:"dark_image_path"`
	DateCreated           types.String `tfsdk:"date_created"`
	DomainName            types.String `tfsdk:"domain_name"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	ExternalID            types.String `tfsdk:"external_id"`
	Groups                []Groups     `tfsdk:"groups"`
	GuidanceMode          types.String `tfsdk:"guidance_mode"`
	ID                    types.Int64  `tfsdk:"id"`
	ImagePath             types.String `tfsdk:"image_path"`
	InventoryLevel        types.String `tfsdk:"inventory_level"`
	LastSync              types.String `tfsdk:"last_sync"`
	LastSyncDuration      types.Int64  `tfsdk:"last_sync_duration"`
	LastUpdated           types.String `tfsdk:"last_updated"`
	Location              types.String `tfsdk:"location"`
	Name                  types.String `tfsdk:"name"`
	NetworkDomain         *Account     `tfsdk:"network_domain"`
	NetworkServer         *Account     `tfsdk:"network_server"`
	NextRunDate           types.String `tfsdk:"next_run_date"`
	Owner                 *Account     `tfsdk:"owner"`
	ProvisioningProxy     types.String `tfsdk:"provisioning_proxy"`
	RegionCode            types.String `tfsdk:"region_code"`
	ScalePriority         types.Int64  `tfsdk:"scale_priority"`
	SecurityMode          types.String `tfsdk:"security_mode"`
	SecurityServer        *Account     `tfsdk:"security_server"`
	ServerCount           types.Int64  `tfsdk:"server_count"`
	ServiceVersion        types.String `tfsdk:"service_version"`
	Stats                 *Stats       `tfsdk:"stats"`
	Status                types.String `tfsdk:"status"`
	StatusDate            types.String `tfsdk:"status_date"`
	StatusMessage         types.String `tfsdk:"status_message"`
	StorageMode           types.String `tfsdk:"storage_mode"`
	Timezone              types.String `tfsdk:"timezone"`
	UserDataLinux         types.String `tfsdk:"user_data_linux"`
	UserDataWindows       types.String `tfsdk:"user_data_windows"`
	UUID                  types.String `tfsdk:"uuid"`
	Visibility            types.String `tfsdk:"visibility"`
	ZoneType              *ZoneType    `tfsdk:"zone_type"`
	ZoneTypeID            types.Int64  `tfsdk:"zone_type_id"`
}
