// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Config struct {
	ZoneAwsConfig     *ZoneAwsConfig     `tfsdk:"zone_aws_config"`
	ZoneAzureConfig   *ZoneAzureConfig   `tfsdk:"zone_azure_config"`
	ZoneGcpConfig     *ZoneGcpConfig     `tfsdk:"zone_gcp_config"`
	ZoneVcenterConfig *ZoneVcenterConfig `tfsdk:"zone_vcenter_config"`
}
