// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ZoneCredential struct {
	ZoneCredential1 *ZoneCredential1 `tfsdk:"zone_credential_1"`
	ZoneCredential2 *ZoneCredential2 `tfsdk:"zone_credential_2"`
}
