// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ServerCounts struct {
	All           types.Int64 `tfsdk:"all"`
	Baremetal     types.Int64 `tfsdk:"baremetal"`
	ContainerHost types.Int64 `tfsdk:"container_host"`
	Host          types.Int64 `tfsdk:"host"`
	Hypervisor    types.Int64 `tfsdk:"hypervisor"`
	Unmanaged     types.Int64 `tfsdk:"unmanaged"`
	VM            types.Int64 `tfsdk:"vm"`
}
