// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ZoneCreate2 struct {
	Code types.String `tfsdk:"code"`
}
