// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ZoneCreate1 struct {
	ID types.Int64 `tfsdk:"id"`
}
