// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"newtest/internal/sdk/pkg/models/shared"
)

type AddCloudsRequestBody struct {
	Zone shared.ZoneCreate `json:"zone"`
}

// AddClouds200ApplicationJSON - Successful Request
type AddClouds200ApplicationJSON struct {
	Success *bool        `json:"success,omitempty"`
	Zone    *shared.Zone `json:"zone,omitempty"`
}

type AddCloudsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful Request
	AddClouds200ApplicationJSONObject *AddClouds200ApplicationJSON
	// Error Codes
	DefaultError *shared.DefaultError
}
