// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"newtest/internal/sdk/pkg/models/shared"
)

type SetApplianceSettingsMaintenanceModeRequest struct {
	// Pass true to turn on maintenance mode, or false to turn it off. If no value is given then it will be toggled from off to on or vice versa.
	Enabled *bool `queryParam:"style=form,explode=true,name=enabled"`
}

type SetApplianceSettingsMaintenanceModeResponse struct {
	// Successful Response
	TwoHundredSuccess *shared.TwoHundredSuccess
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error Codes
	DefaultError *shared.DefaultError
}
